In [2]:
# Loading all 3 files generated by the code generator
import pandas as pd

beneficiaries = pd.read_csv('../data/raw/beneficiaries.csv')
national_ids = pd.read_csv('../data/raw/national_id_records.csv')
disbursements = pd.read_csv('../data/raw/disbursements.csv')

print("Beneficiaries Shape:", beneficiaries.shape)
print("National IDs Shape:", national_ids.shape)
print("Disbursements Shape:", disbursements.shape)

Beneficiaries Shape: (10100, 18)
National IDs Shape: (10000, 8)
Disbursements Shape: (38846, 9)

In [3]:
#raw shape of each dataset
beneficiaries.head()

,beneficiary_id,full_name,father_or_husband_name,gender,date_of_birth,cnic,phone_number,marital_status,household_size,monthly_income_pkr,address_line,city,province,bank_account_number,welfare_program,registration_date,registration_channel,status
0,BEN-000001,Renee Pacheco,Scott Jones,F,06/10/1987,79656-8882190-6,0345-5628372,Widowed,3,5000.0,01494 Curtis Shoals Apt. 027,Hyderabad,Sindh,PK7462842783993250,Cash Transfer Program,2019-05-23,In-Person Center,Inactive
1,BEN-000002,Stacey Stephens,Jorge Gibson,Female,1995-09-17,53731-8514737-6,0310-6267222,Married,3,15000.0,3229 Miguel Court,SIBI,Balochistan,PK8016893386937535,Cash Transfer Program,2022-06-17,Online Portal,Active
2,BEN-000003,Colleen Young,Victor Mccarty,Female,23/01/1971,39783-8040484-3,0345-4699888,Widowed,3,5000.0,674 Myers Squares Apt. 866,Swat,Khyber Pakhtunkhwa,PK1689755665922203,Elderly Pension Program,2022-04-09,Online Portal,Active
3,BEN-000004,Chloe Morales,Philip Smith,Female,31/08/1985,77799-2186330-5,0300-7577796,Divorced,2,15000.0,8351 Wright Well,Sialkot,Punjab,PK7721042279005796,Cash Transfer Program,2020-11-23,In-Person Center,Active
4,BEN-000005,michele smith,Michael Graham,Female,1971-05-09,91957-7587159-9,0310-0462280,Divorced,4,0.0,3477 Evans Radial Apt. 670,Bahawalpur,Punjab,PK2398801517613574,Widow & Orphan Support Program,2019-10-27,Online Portal,Active

In [4]:
beneficiaries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10100 entries, 0 to 10099
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   beneficiary_id          10100 non-null  object
 1   full_name               10100 non-null  object
 2   father_or_husband_name  10100 non-null  object
 3   gender                  10100 non-null  object
 4   date_of_birth           10100 non-null  object
 5   cnic                    10100 non-null  object
 6   phone_number            9441 non-null   object
 7   marital_status          10100 non-null  object
 8   household_size          10100 non-null  int64
 9   monthly_income_pkr      9812 non-null   float64
 10  address_line            9686 non-null   object
 11  city                    10100 non-null  object
 12  province                10100 non-null  object
 13  bank_account_number     10100 non-null  object
 14  welfare_program         10100 non-null  object
 15  registration_date       10100 non-null  object
 16  registration_channel    10100 non-null  object
 17  status                  10100 non-null  object
dtypes: float64(1), int64(1), object(16)
memory usage: 1.4+ MB

In [5]:
beneficiaries.describe()

       household_size  monthly_income_pkr
count    10100.000000         9812.000000
mean         5.520792        21187.312169
std          7.755693        96102.490501
min         -1.000000        -5000.000000
25%          3.000000         5000.000000
50%          5.000000        12000.000000
75%          7.000000        20000.000000
max         99.000000       999999.000000

In [6]:
beneficiaries.dtypes

beneficiary_id             object
full_name                  object
father_or_husband_name     object
gender                     object
date_of_birth              object
cnic                       object
phone_number               object
marital_status             object
household_size              int64
monthly_income_pkr        float64
address_line               object
city                       object
province                   object
bank_account_number        object
welfare_program            object
registration_date          object
registration_channel       object
status                     object
dtype: object

## beneficiaries.csv - Data Dictionary
| Column Name | Data Type | Description
| --- | --- | ---
| beneficiary_id | int | Unique identifier for each beneficiary
| full_name | str | Full name of the beneficiary
| father_or_husband_name | str | Name of the beneficiary's father or husband
| gender | str | Gender of the beneficiary (Male/Female)
| date_of_birth | str | Date of birth of the beneficiary (YYYY-MM-DD)
| cnic | str | National Identity Card number of the beneficiary
| phone_number | str | Contact phone number of the beneficiary
| marital_status | str | Marital status of the beneficiary (Single/Married/Divorced/Widowed)
| household_size | int | Number of individuals in the beneficiary's household
| income | float | Monthly income of the beneficiary in local currency
| address | str | Residential address of the beneficiary
| city | str | City of residence of the beneficiary
| province | str | Province of residence of the beneficiary
| bank_account_number | str | Bank account number of the beneficiary for receiving disbursements
| welfare_program | str | Name of the welfare program the beneficiary is enrolled in
| registration_date | str | Date when the beneficiary was registered in the welfare program (YYYY-MM-DD)
| registration_title | str | Title of the registration document for the beneficiary
| status | str | Current status of the beneficiary (Active/Inactive/Suspended)

In [7]:
national_ids.head()

,national_id_no,full_name,gender,date_of_birth,address,id_issue_date,id_status,linked_beneficiary_id
0,61263-2582537-5,Thomas Welch,Male,1991-06-17,"0430 Miller Estates, Michaelhaven, Punjab",2025-08-09,Expired,NaN
1,59126-0671442-4,Christopher JaCkson,Male,1947-07-28,"938 Cohen Garden, Gwadar, Balochistan",2014-12-30,Active,BEN-001768
2,39306-3211568-9,Luis Kane,Male,1967-12-08,"Sindh, Karachi, 0078 Alicia Drive",2016-03-28,Active,BEN-001411
3,03594-7836724-1,Christopher Williams,Male,1972-04-16,"874 Goodman Inlet Suite 299, Mardan, Khyber Pa...",2012-03-07,Active,BEN-005147
4,36424-4316708-9,Scott Jarvis,Male,2004-11-14,"6194 Mcmillan Burgs, Lewishaven, Punjab",2013-05-25,Active,NaN

In [8]:
national_ids.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   national_id_no         10000 non-null  object
 1   full_name              10000 non-null  object
 2   gender                 10000 non-null  object
 3   date_of_birth          10000 non-null  object
 4   address                9668 non-null   object
 5   id_issue_date          10000 non-null  object
 6   id_status              9820 non-null   object
 7   linked_beneficiary_id  8000 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [9]:
national_ids.describe()

,national_id_no,full_name,gender,date_of_birth,address,id_issue_date,id_status,linked_beneficiary_id
count,10000,10000,10000,10000,9668,10000,9820,8000
unique,10000,9659,2,8626,9668,4388,2,8000
top,61263-2582537-5,Robert Smith,Female,2005-07-28,"0430 Miller Estates, Michaelhaven, Punjab",2020-06-24,Active,BEN-001768
freq,1,6,5049,5,1,9,7366,1

In [10]:
national_ids.dtypes

national_id_no           object
full_name                object
gender                   object
date_of_birth            object
address                  object
id_issue_date            object
id_status                object
linked_beneficiary_id    object
dtype: object

## national_id_record - Data Dictionary
| Column Name | Data Type | Description
| --- | --- | ---
| national_id_no | string | Unique identifier for each individual in the national ID records.
| full_name | string | Full name of the individual as recorded in the national ID records.
| gender | string | Gender of the individual (e.g., Male, Female, Other).
| date_of_birth | date | Date of birth of the individual in the format YYYY-MM-DD.
| address | string | Residential address of the individual as recorded in the national ID records.
| id_issued_date | date | The date when the national ID was issued to the individual in the format YYYY-MM-DD.
| id_status | string | Status of the national ID (e.g., Active, Inactive, Expired).
| linked_beneficiary_id | string | The unique identifier linking the national ID record to a beneficiary in the beneficiaries dataset.

In [11]:
disbursements.head()

,disbursement_id,beneficiary_id,bank_account_number,amount_pkr,disbursement_cycle,disbursement_date,payment_method,branch_or_agent_code,status
0,DSB-0007344,BEN-002215,PK6132180624367744,"6,000",2025-02,NaN,Bank Transfer,BR-294,Success
1,DSB-0030734,BEN-009193,PK1537012347720164,10000,2025-03,2025-03-14,Mobile Wallet,BR-163,Success
2,DSB-0019450,BEN-005854,PK2701804089111106,7500,2025-06,2025-06-16,Bank Transfer,BR-106,Pending
3,DSB-0008116,BEN-002452,PK6172884550113990,6000,2025-04,2025-04-05,Mobile Wallet,BR-182,Pending
4,DSB-0014107,BEN-004223,PK7474852407746966,5000,2025-04,2025-04-08,Cash Pickup,BR-192,Success

In [12]:
disbursements.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38846 entries, 0 to 38845
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   disbursement_id       38846 non-null  object
 1   beneficiary_id        38846 non-null  object
 2   bank_account_number   38846 non-null  object
 3   amount_pkr            38846 non-null  object
 4   disbursement_cycle    38846 non-null  object
 5   disbursement_date     37715 non-null  object
 6   payment_method        38130 non-null  object
 7   branch_or_agent_code  38846 non-null  object
 8   status                38846 non-null  object
dtypes: object(9)
memory usage: 2.7+ MB

In [13]:
disbursements.describe()

,disbursement_id,beneficiary_id,bank_account_number,amount_pkr,disbursement_cycle,disbursement_date,payment_method,branch_or_agent_code,status
count,38846,38846,38846,38846,38846,37715,38130,38846,38846
unique,38272,6418,6198,25,6,168,3,200,8
top,DSB-0015832,BEN-003857,PK3620877530936338,7500,2025-04,2025-03-09,Mobile Wallet,BR-289,Success
freq,2,12,31,6685,6509,261,12724,234,22957

In [14]:
disbursements.dtypes

disbursement_id         object
beneficiary_id          object
bank_account_number     object
amount_pkr              object
disbursement_cycle      object
disbursement_date       object
payment_method          object
branch_or_agent_code    object
status                  object
dtype: object

## disbursements.csv - Data Dictionary
| Column Name | Data Type | Description
| --- | --- | ---
| disbursement_id | int | Unique identifier for each disbursement record
| beneficiary_id | int | Unique identifier for each beneficiary
| bank_account_number | str | Bank account number of the beneficiary
| amount_pkr | int | Amount disbursed in Pakistani Rupees
| disbursement_cycle | str | Disbursement cycle (e.g., monthly, quarterly)
| disbursement_date | datetime | Date of the disbursement
| payment_method | str | Method of payment (e.g., bank transfer, cash)
| branch_or_agent | str | Branch or agent responsible for the disbursement
| status | str | Status of the disbursement (e.g., completed, pending, failed)

In [15]:
# Check for missing values in each dataset
print("Missing values in Beneficiaries dataset:\n", beneficiaries.isnull().sum())

Missing values in Beneficiaries dataset:
 beneficiary_id              0
full_name                   0
father_or_husband_name      0
gender                      0
date_of_birth               0
cnic                        0
phone_number              659
marital_status              0
household_size              0
monthly_income_pkr        288
address_line              414
city                        0
province                    0
bank_account_number         0
welfare_program             0
registration_date           0
registration_channel        0
status                      0
dtype: int64

In [16]:
# Check for missing values in national_ids dataset
print("Missing values in National IDs dataset:\n", national_ids.isnull().sum())

Missing values in National IDs dataset:
 national_id_no              0
full_name                   0
gender                      0
date_of_birth               0
address                   332
id_issue_date               0
id_status                 180
linked_beneficiary_id    2000
dtype: int64

In [17]:
# Check for missing values in disbursements dataset
print("Missing values in Disbursements dataset:\n", disbursements.isnull().sum())

Missing values in Disbursements dataset:
 disbursement_id            0
beneficiary_id             0
bank_account_number        0
amount_pkr                 0
disbursement_cycle         0
disbursement_date       1131
payment_method           716
branch_or_agent_code       0
status                     0
dtype: int64

In [18]:
beneficiaries.duplicated().sum()                      # fully duplicate rows

np.int64(100)

In [19]:
beneficiaries["beneficiary_id"].duplicated().sum()     # duplicate IDs (should be 0 — it's a primary key)

np.int64(100)

In [20]:
beneficiaries["cnic"].duplicated().sum()                # duplicate CNICs -- interesting if > 0!

np.int64(100)

In [21]:
beneficiaries["bank_account_number"].duplicated().sum() # duplicate bank accounts -- THIS is a fraud signal

np.int64(100)

In [22]:
# Why this matters a duplicate bank_account_number in the beneficiary registry itself, or heavily duplicated in disbursements, is one of your core fraud patterns.
disbursements["bank_account_number"].value_counts().head(10)

bank_account_number
PK3620877530936338    31
PK6926748636544594    29
PK8791131063845457    29
PK3536878316458124    29
PK6157813831282564    29
PK1818741521038979    29
PK0204128252242003    29
PK4503796472503908    29
PK6913512647286211    29
PK5493263564317808    29
Name: count, dtype: int64

In [23]:
national_ids["national_id_no"].duplicated().sum()

np.int64(0)

In [24]:
national_ids['linked_beneficiary_id'].duplicated().sum()

np.int64(1999)

## does the spread of values make sense?

In [25]:
national_ids['linked_beneficiary_id'].value_counts().head(10)

linked_beneficiary_id
BEN-001768    1
BEN-004334    1
BEN-006271    1
BEN-007004    1
BEN-009233    1
BEN-009651    1
BEN-009017    1
BEN-005964    1
BEN-001515    1
BEN-003717    1
Name: count, dtype: int64

In [26]:
beneficiaries['status'].value_counts()

status
Active       5388
Inactive     1850
Suspended    1815
active        262
ACTIVE        244
Actve         223
inactive      162
suspended     156
Name: count, dtype: int64

In [27]:
beneficiaries['province'].value_counts()

province
Sindh                 2543
Khyber Pakhtunkhwa    2530
Punjab                2520
Balochistan           2507
Name: count, dtype: int64

In [28]:
beneficiaries['welfare_program'].value_counts()

welfare_program
Flood Relief Assistance           2051
Widow & Orphan Support Program    2021
Elderly Pension Program           2016
Cash Transfer Program             2009
Disability Support Program        2003
Name: count, dtype: int64

In [29]:
disbursements['status'].value_counts()

status
Success     22957
Pending      6034
Reversed     6000
Succes        989
SUCCESS       964
success       962
pending       476
reversed      464
Name: count, dtype: int64

In [30]:
disbursements['disbursement_cycle'].value_counts()

disbursement_cycle
2025-04    6509
2025-03    6482
2025-07    6482
2025-06    6481
2025-05    6473
2025-02    6419
Name: count, dtype: int64

## .describe() gives min, max, mean, and percentiles. 
### Any impossible values (negative income, a zero disbursement, an oddly huge outlier amount)?

In [31]:
beneficiaries["monthly_income_pkr"].describe()

count      9812.000000
mean      21187.312169
std       96102.490501
min       -5000.000000
25%        5000.000000
50%       12000.000000
75%       20000.000000
max      999999.000000
Name: monthly_income_pkr, dtype: float64

In [32]:
disbursements["amount_pkr"].describe()

count     38846
unique       25
top        7500
freq       6685
Name: amount_pkr, dtype: object

## Cross Check the relationship between three files

In [33]:
# How many beneficiary IDs in disbursements DON'T exist in beneficiaries.csv?
orphan_ids = set(disbursements["beneficiary_id"]) - set(beneficiaries["beneficiary_id"])
print("Orphan beneficiary IDs in disbursements:", len(orphan_ids))

Orphan beneficiary IDs in disbursements: 25

In [34]:
# How many beneficiaries have NO matching national ID record?
matched_ids = set(national_ids["linked_beneficiary_id"].dropna())
unmatched = set(beneficiaries["beneficiary_id"]) - matched_ids
print("Beneficiaries with no national ID match:", len(unmatched))

Beneficiaries with no national ID match: 2000

In [35]:
# Do CNIC formats match exactly between beneficiaries.csv and national_id_records.csv?
merged_check = beneficiaries.merge(
    national_ids, left_on="beneficiary_id", right_on="linked_beneficiary_id", how="inner"
)
mismatch_count = (merged_check["cnic"] != merged_check["national_id_no"]).sum()
print("CNIC mismatches between the two systems:", mismatch_count)

CNIC mismatches between the two systems: 559

In [36]:
missing_cnic = set(beneficiaries["cnic"]) - set(national_ids["national_id_no"])
print("CNICs in beneficiaries.csv but not in national_id_records.csv:", len(missing_cnic))
print("Missing CNICs:", missing_cnic)

CNICs in beneficiaries.csv but not in national_id_records.csv: 2556

In [37]:
# Remove dashes, spaces, and convert to string to preserve leading zeros
beneficiaries['cnic_clean'] = beneficiaries['cnic'].astype(str).str.replace(r'[^0-9]', '', regex=True)
national_ids['cnic_clean'] = national_ids['national_id_no'].astype(str).str.replace(r'[^0-9]', '', regex=True)

In [38]:
# 1. Raw Mismatches (with formatting like dashes)
raw_mismatches = set(beneficiaries['cnic']) - set(national_ids['national_id_no'])

# 2. Clean Mismatches (pure numbers only)
clean_mismatches = set(beneficiaries['cnic_clean']) - set(national_ids['cnic_clean'])

# 3. The Diagnosis
formatting_failures = len(raw_mismatches) - len(clean_mismatches)
true_missing = len(clean_mismatches)

print(f"Format-related mismatches (fixed by cleaning): {formatting_failures}")
print(f"True mismatches (CNIC completely missing): {true_missing}")

Format-related mismatches (fixed by cleaning): 0
True mismatches (CNIC completely missing): 2556

In [39]:
# Find structurally broken CNICs in beneficiaries
beneficiaries['digit_count'] = beneficiaries['cnic_clean'].str.len()

# Filter for rows that are not exactly 13 digits long
invalid_length_beneficiaries = beneficiaries[beneficiaries['digit_count'] != 13]

print("Rows with invalid CNIC lengths (should be 13 digits):")
print(invalid_length_beneficiaries[['cnic', 'digit_count']])

Rows with invalid CNIC lengths (should be 13 digits):
Empty DataFrame
Columns: [cnic, digit_count]
Index: []

In [43]:
# 1. Merge the systems on beneficiary ID
merged_check = beneficiaries.merge(
    national_ids, left_on="beneficiary_id", right_on="linked_beneficiary_id", how="inner"
)

# 2. Filter for rows where the CNIC numbers do not match
mismatches_df = merged_check[merged_check["cnic"] != merged_check["national_id_no"]]

# 3. Create a clean report showing the differences using the correct pandas default suffixes (_x, _y)
cnic_mismatch_report = mismatches_df[[
    'beneficiary_id', 
    'full_name_x',       # Name recorded in beneficiaries registry
    'full_name_y',       # Name recorded at NADRA national database
    'cnic',              # CNIC recorded in welfare program
    'national_id_no'     # Actual CNIC recorded at NADRA
]].copy()

# Rename columns for perfect readability
cnic_mismatch_report.columns = ['ID', 'Welfare Name', 'NADRA Name', 'Welfare CNIC', 'NADRA CNIC']

print(f"Total Discrepancies Found: {len(cnic_mismatch_report)}")
cnic_mismatch_report.head(50)

Total Discrepancies Found: 559

,ID,Welfare Name,NADRA Name,Welfare CNIC,NADRA CNIC
19,BEN-000025,Barbara Smith,Barbara Smith,47171-0649181-8,47171-4649181-8
24,BEN-000030,Joshua Weber,Joshua Weber,54053-8790270-3,54953-8790270-3
33,BEN-000040,Lisa Schroeder,LISA SCHROEDER,16920-3907662-3,16920-3007662-3
34,BEN-000041,Tiffany Bridges,Tiffany Bridges,76180-3156434-4,76180-3116434-4
44,BEN-000055,SARAH GOODWIN,Sarah Goodwin,03998-6782463-1,09998-6782463-1
66,BEN-000083,Jill Ramos,Jill Rmos,20947-9381171-3,20947-9381141-3
92,BEN-000114,Karl Coleman,Karl Coleman,18744-1208294-7,18744-6208294-7
100,BEN-000123,Brandy Wu,brandy wu,50224-4335543-0,50224-4335523-0
103,BEN-000126,brittany watson,Brittany Watson,92784-5422514-3,92784-5422214-3
106,BEN-000129,Debra Brown,Debra Brown,26939-7361056-2,26939-7261056-2
158,BEN-000192,Michael Wright,Michael Wright,70492-5528548-4,70492-5528048-4
159,BEN-000193,Jonathan Rocha,Jonathan Rocha,91956-5769305-2,91956-5719305-2
178,BEN-000217,Angela Owen,Angela Owen,90605-7889783-7,90905-7889783-7
187,BEN-000231,Nathaniel Hoffman,Nathaniel Hoffman,33184-9754639-6,33184-9750639-6
189,BEN-000234,Seth Coffey,Seth Coffey,82174-8139961-1,82274-8139961-1
229,BEN-000279,Nicholas Hines,Nicolas Hines,66413-9425628-0,63413-9425628-0
244,BEN-000295,Jeffery Stout,Jeffery Stout,79718-7922904-2,79718-7922504-2
255,BEN-000307,Megan Johnson,Megan Johnson,04082-5972707-8,04082-5972607-8
262,BEN-000315,Kimberly Taylor,Kimberly Taylor,13194-7288824-9,13194-7288124-9
290,BEN-000345,peter wise,PETER WISE,38825-5266643-1,39825-5266643-1
325,BEN-000388,donald jimenez dds,Donald Jimenez DDS,52908-3071854-0,52908-3071864-0
329,BEN-000392,Robert Potts,RobertPotts,48919-7526360-7,48919-6526360-7
344,BEN-000409,AMY FITZPATRICK,Amy Fitzpatrick,28220-1664042-6,78220-1664042-6
346,BEN-000411,Mitchell Cook,Mitchell Cook,57910-7371544-3,57910-6371544-3
349,BEN-000416,Tonya Lee,Tonya Lee,38516-6622833-6,38516-6623833-6
372,BEN-000445,Douglas Martin,Douglas Martin,73474-4604774-6,73474-2604774-6
373,BEN-000446,Fernando Wade,Fenrando Wade,38734-5422452-3,38734-5425452-3
390,BEN-000465,karen scott,Karen Scott,99628-8548873-4,99628-8448873-4
401,BEN-000477,Austin Clements,Austin Clements,73494-6601404-4,73494-6621404-4
415,BEN-000493,Joshua Haley,Joshua Haley,99404-7641845-8,99404-7641845-1
443,BEN-000528,Anthony Fisher,Anthony Fisher,36975-2996274-4,36975-2996574-4
463,BEN-000556,Lynn Sandoval,Lynn Sandoval,79561-0173956-1,79561-0173966-1
470,BEN-000567,Jeffrey Osborne,Jeffrey Osborne,63401-8179555-2,53401-8179555-2
472,BEN-000569,Jared Davis,JaRed Davis,83767-8234525-2,83767-8233525-2
492,BEN-000593,Marcus Tran,Marcus Tran,01789-2949532-9,01789-2959532-9
507,BEN-000612,Amber Cisneros,Amber Cisneros,58868-6054408-1,98868-6054408-1
512,BEN-000617,Matthew Baker,Matthew Baker,92535-3054327-9,32535-3054327-9
540,BEN-000653,Donna White,Donna White,25723-3166274-1,25723-3166278-1
548,BEN-000664,Tyler Johnson,Tyler Johnson,88732-8347916-9,84732-8347916-9
552,BEN-000669,Peter Atkins,Peter Atkins,94167-5406724-1,64167-5406724-1
561,BEN-000680,Mackenzie Kennedy,Mackenzie Kennedy,48491-2667355-2,48491-2667755-2
566,BEN-000685,Maureen Smith,MAUREEN SMITH,84785-8062075-6,84385-8062075-6
597,BEN-000721,David Beltran,David Beltran,41072-1613778-0,41072-1612778-0
642,BEN-000784,SCOTT MILLER,Scott Miller,33387-2985102-1,33387-2985103-1
644,BEN-000787,Thomas Washington,Thomas Washington,40802-4932843-4,40832-4932843-4
648,BEN-000791,Laura Nelson,Laura Nelson,28697-2474941-5,28697-2374941-5
654,BEN-000797,Kevin Reyes,Kevin Reyes,92150-5654953-5,92150-0654953-5
658,BEN-000803,Desiree Miles,Desiree Miles,32428-9140928-1,32428-9940928-1
659,BEN-000804,Troy Parker,Troy Parker,36985-6510125-0,36985-6410125-0
670,BEN-000820,Alisha Alvarez,Alisha lAvarez,10147-5867803-7,10147-5887803-7

In [44]:
values = beneficiaries['monthly_income_pkr'] > 10000
values

0        False
1         True
2        False
3         True
4        False
         ...
10095    False
10096     True
10097    False
10098    False
10099     True
Name: monthly_income_pkr, Length: 10100, dtype: bool

In [45]:
disbursements["amount_pkr"].unique()

array(['6,000', '10000', '7500', '6000', '5000', '8000', '10,000',
       '5,000', 'Rs. 5,000', '7,500', '-5000.0', 'Rs. 6,000',
       'Rs. 10,000', 'Rs. 8,000', '8,000', '120000.0', 'Rs. 7,500',
       '200000.0', '-10000.0', '150000.0', '-6000.0', '-8000.0',
       '100000.0', '-7500.0', '160000.0'], dtype=object)